# Generated by Django 4.2.11 on 2024-03-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='max_marks',
            field=models.PositiveIntegerField(default=50),
            preserve_default=False,
        ),
    ]
